name: Deploy to IPFS

on:
  push:
    branches:
      - master
      - TECH-*

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Deploy to IPFS
        id: ipfs
        uses: aquiladev/ipfs-action@master
        with:
          path: ../mips/MIP*
          service: filebase
          pinName: 'mips-${{ vars.ENV }}'
          filebaseBucket: ${{ secrets.FILEBASE_BUCKET }}
          filebaseKey: ${{ secrets.FILEBASE_KEY }}
          filebaseSecret: ${{ secrets.FILEBASE_SECRET }}

      - name: Update DNSLink record in Cloudflare
        id: cloudflare-dnslink
        run: |
          curl --request PATCH \
            --url https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/web3/hostnames/${{ secrets.CLOUDFLARE_HOSTNAME_ID }} \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H 'Content-Type: application/json' \
            --data '{
            "description": "DNS record for MIPs on IPFS",
            "dnslink": "/ipfs/${{ steps.ipfs.outputs.cid }}"
          }'
